name: Deploy to Prod

on:
  push:
    branches:
    - prod


jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.4.1
        with:
          version: v0.2.7
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Rojo
        run: rojo build -o place.rbxl
        
      - name: Deploy to Roblox
        run: rbxcloud experience publish -f place.rbxl -p 14823168927 -u 5108142293 -t published -a ${{ secrets.ROBLOX_PROD_KEY }}

    